name: Docker-Hostinger-Deployment
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t my-app .

      - name: Save Docker image as a tarball
        run: docker save my-app | gzip > my-app.tar.gz

      - name: Upload Docker image to Hostinger
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOSTINGER_IP }}
          username: abubakar
          key: ${{ secrets.HOSTINGER_SSH_KEY }}
          source: my-app.tar.gz
          target: /home/abubakar/

      - name: SSH into Hostinger and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOSTINGER_IP }}
          username: abubakar
          key: ${{ secrets.HOSTINGER_SSH_KEY }}
          script: |
            gunzip /home/abubakar/my-app.tar.gz
            docker load < /home/abubakar/my-app.tar
            docker rm -f my-app || true
            docker run -d -p 5173:3000 --name my-app my-app
